import express from"express";
import{chromium}from"playwright";
import fs from"fs";
import{gunzipSync}from"zlib";
let app=express(),port=process.env.PORT||3000,state=process.env.STATE_PATH||"state.json",url="https://mijnknltb.toernooi.nl/",cache=null,cacheAt=0,ttl=15*60*1000;
if(process.env.KNLTB_STATE&&!fs.existsSync(state))fs.writeFileSync(state,gunzipSync(Buffer.from(process.env.KNLTB_STATE,"base64")));
async function page(){let b=await chromium.launch({headless:true,args:["--no-sandbox"]}),ctx=fs.existsSync(state)?await b.newContext({storageState:state}):await b.newContext();await ctx.route("**/*",r=>{let u=r.request().url(),m=r.request().method();if(m!="GET"||/loginnaam|username|forgot|password|wachtwoord|logoff/i.test(u))return r.abort();r.continue()});let p=await ctx.newPage();return{b,p}}
function loggedOut(text,href){return /loginnaam vergeten|wachtwoord vergeten|voortaan is mijnknltb alleen toegankelijk na inloggen|Log in|INLOGGEN/.test(text)&&!/Joost van Oord|Mijn profiel|Bondsnummer/.test(text)||/login|signin|account/i.test(href)&&!/mijnknltb.toernooi.nl/$/.test(href)}
async function readHome(){let{b,p}=await page();try{await p.goto(url,{waitUntil:"commit",timeout:20000});await p.waitForTimeout(3000);let href=p.url(),text=(await p.textContent("body")||"").trim();if(loggedOut(text,href)){let e=new Error("KNLTB_LOGIN_REQUIRED");e.status=401;throw e}let links=await p.$$eval("a",a=>a.map(x=>({text:x.innerText.trim(),href:x.href})));return{text,links}}finally{await b.close().catch(()=>{})}}
let lines=t=>t.split(/\n+/).map(x=>x.trim()).filter(Boolean),pick=(a,s)=>a.findIndex(x=>x==s),after=(a,s,n=1)=>a[pick(a,s)+n]||"";
function parse(text,links=[]){let a=lines(text),name=after(a,"Mijn profiel",5)||a.find(x=>/^[A-Z][a-z]+ .*oord/i.test(x))||"",bond=(text.match(/\((\d{6,})\)/)||[])[1]||"",ratings=[...text.matchAll(/\b9\s+([0-9],[0-9]{4})\b/g)].map(x=>x[1]),wi=pick(a,"Volgende wedstrijd"),pi=pick(a,"Mijn profiel"),w=a.slice(wi,pi>wi?pi:wi+40),teams=w.map((x,i)=>/\(#\d+\)/.test(w[i+1]||"")?x:"-").filter(x=>x!="-"),forms=[...w.join(" ").matchAll(/\b([WVG](?:\s+[WVG]){4})\b/g)].map(x=>x[1].replace(/\s/g,"")),date=(w.find(x=>/\d{4}\d{1,2}:\d{2}/.test(x))||"").replace(/(\d{4})(\d{1,2}:\d{2})/,"$1 $2"),comp=w[1]||"",klasse=w[2]||"",wl=(text.match(/Carrière\s+(\d+\s*\/\s*\d+\s*\(\d+\))/)||[])[1]||"",year=(text.match(/Dit jaar\s+(\d+\s*\/\s*\d+\s*\(\d+\))/)||[])[1]||"",hist=(text.match(/Historie\s+([WV\s]{5,})/)||[])[1]?.replace(/\s/g,"").slice(0,5)||"";let stand=[],di=links.findIndex(x=>/Afdeling 16/.test(x.text));if(di>-1)for(let x of links.slice(di+1)){if(/^Spelers van/.test(x.text))break;if(/team\/\d+/.test(x.href)&&x.text)stand.push(x.text)}let tournaments=[],ti=links.findIndex(x=>x.text=="TOERNOOIEN"||x.text=="ALLE INSCHRIJVINGEN");for(let i=Math.max(0,ti);i<links.length;i++){let x=links[i];if(/sport\/tournament\?id=/.test(x.href)&&x.text&&!/KNLTB voorjaar/.test(x.text)){let ev=(links.slice(i+1).find(y=>/sport\/event/.test(y.href)&&y.text)||{}).text||"";tournaments.push({name:x.text,event:ev})}}return{name,bond,ratings:{single:ratings[0]||"",double:ratings[1]||""},record:{career:wl,year,hist},next:{comp,klasse,date,home:teams[0]||"",away:teams[1]||"",forms},stand:[...new Set(stand)],tournaments}}
async function fresh(){let{text,links}=await readHome();return{ok:true,data:parse(text,links),raw:text.slice(0,5000),cached:false,time:new Date().toISOString()}}
app.use(express.static("public"));
app.get("/api/health",(req,res)=>res.json({ok:true,time:new Date().toISOString(),hasCache:!!cache}));
app.get("/api/data",async(req,res)=>{try{if(cache&&Date.now()-cacheAt<ttl)return res.json({...cache,cached:true});cache=await fresh();cacheAt=Date.now();res.json(cache)}catch(e){if(cache)return res.json({...cache,cached:true,stale:true,error:e.message});res.status(500).json({ok:false,error:e.message})}});
app.get("/api/refresh",async(req,res)=>{try{cache=await fresh();cacheAt=Date.now();res.json(cache)}catch(e){if(cache)return res.status(e.status||500).json({...cache,cached:true,stale:true,error:e.message});res.status(e.status||500).json({ok:false,error:e.message})}});
app.get("/api/debug/links",async(req,res)=>{if(!process.env.DEBUG_TOKEN||req.query.token!==process.env.DEBUG_TOKEN)return res.status(404).end();try{let{text,links}=await readHome();links=links.filter(x=>/compet|inschrij|toernooi|stand|wedstrijd|team|poule|uitslag/i.test(x.text+" "+x.href));res.json({ok:true,links})}catch(e){res.status(e.status||500).json({ok:false,error:e.message})}});
app.listen(port,()=>console.log("http://localhost:"+port));
